### ISSUE TITLE
Command to create a whitelist?

### ISSUE THREAD

**Issue by dragnort1** [Chessnut/NutScript#284]
Hi, I was wondering if there is a command to create whitelist or somewhere within the schema setup.
Thanks

Also, on a map which my server is on it is darker than other servers, the map mrp_Stations_b3. Is there a fix in the settings?

**Comment by Thadah** [comment]
Not that I know of.

And for the map stuff, NutScript deactivates color correction in the gamemode and I think it changes the gamma too so the colors look sadder. The commands you have to set to prevent that are these:

mat_colorcorrection 1 
sv_allow_color_correction 1

These two commands will enable the server's color correction and allow clients to enable and disable it.

Also, if it's still dark you must assure that you have HDR enabled since it makes the map look brighter and with better lighting.

**Comment by dragnort1** [comment]
Thanks, I'll try the commands now.

**Comment by Thadah** [comment]
You should put them in your server.cfg if you want the server to stay like that every time you reboot it.
