### ISSUE TITLE
[1.1] Tab Menu Icons

### ISSUE THREAD

**Issue by dinguspocket** [Chessnut/NutScript#394]
After various different attempts at fixing these: reloading the icons in the Q menu, and a few console commands - they've remained the same. Which is an error, not only are they an error in the tab menu, but in the f1 menu as well.

**Comment by Chessnut** [comment]
That means you're missing the model?

**Comment by dinguspocket** [comment]
No, I've got  the model. It shows in the character select menu, and in the q menu. However, in both tab and f1 it's an error.

**Comment by Chessnut** [comment]
Well the F1 menu and the character menu use the same exact model display so
there is no way it would differ.

**Comment by dinguspocket** [comment]
http://i.gyazo.com/bcb9008003c649dcb2baff11b54da22a.png - Character Select menu
http://i.gyazo.com/cc2b7449667e23f1f473ab79050dea27.png - F1 menu

**Comment by Chessnut** [comment]
Did you or your schema/plugins change the player model after spawning? Are
there errors?

**Comment by DeadiKation** [comment]
No, There are no errors (He's talking about our server)

I recently uploaded these to the server, and players have them locally. They're mounted on the server, and everyone can see / interact with the models, playermodels, and when they die no errors. But only when getting the "Spawn icons" of these models for Tab menu and F1 Menu, will it show errors, no where else. Q Menu is fine, Spawning is fine.

**Comment by Serconker** [comment]
This is a problem I've noticed with GMod for a while.
Instead of regenerating a models icon every time it, caches them and if it's an error it'll stay an error until the cache is released, I have no idea where said cache is but the only way I've found of clearing said cache is to reinstall.
(Basically, if you come on the server and don't have the models and view the scoreboard it's gonna render them as errors and keep that until it's refreshed)


Though in the spawn menu you can refresh it and it'll reload that icon, one thing you could do is add a console command to reload the model icons in the character screens and maybe that'd work?

Not sure as to why it's doing that in the F1 menu though, the model derma panel does reload the model every time it's loaded.

Either way it's a wild guess at how it works.

**Comment by DeadiKation** [comment]
We actually fixed it, so you can close this. The models were compiled under a mis-name and were given to players while the model was calling a different name. Not a nutscript issue

Close please <3
