### ISSUE TITLE
[1.1] Door child/parent problem

### ISSUE THREAD

**Issue by RobinPrette** [Chessnut/NutScript#462]
I found a curious glitch, you need at least two doors :
1. Set door `1` to parent
2. Set door `2` to child
3. After, set door `2` to parent
4. Set door `1` to child
5. Buy one of the two doors
6. Garry's mod immediately freezing

I tried to do this with double doors : when I want to buy the first door, the second one is bought automatically.

**Comment by Chessnut** [comment]
Door 1 belongs to door 2
You made door 2 belong to door 1

When you buy a door, it sets the owner for all child doors.

So door 1 sets it child then sets door 2's child, since door 2 is also the parent of door 1 it sets the child of door 1, which sets the child of door 2.

So you made an infinite loop, but why did you do this in the first place?

**Comment by RobinPrette** [comment]
Yeah it's an infinite loop, on server's console you have : 

![infinite loop serverside](https://cloud.githubusercontent.com/assets/12173101/7428968/5b567504-eff9-11e4-9916-5426d38c858b.png)

I did that for double doors, I want that when a player buys the door 1, the door 2 is automatically bought. For the moment the player needs to buy both of them.

![double door screenshot](http://images.akamai.steamusercontent.com/ugc/716413856111739632/93F9BF59D47DDF4374C08F613C6740D137A328D5/)

**Comment by Chessnut** [comment]
You should just be able to purchase the child door and the parent door will be purchased.

**Comment by FlammableAce** [comment]
You only have to set one parent door and if you buy the child door it will buy the parent door to.
