### ISSUE TITLE
ULX Give physgun?

### ISSUE THREAD

**Issue by Lockdown10** [Chessnut/NutScript#480]
I've recently downloaded NS; HL2RP, with the ULX ULIB Admin Mod, but I can't figure out how to give character physgun or tool gun, how do I do this?

**Comment by Syndyr** [comment]
First of all, why are you using ULX?
Anyway, you can give that character the P and T flags with "/flaggive PT", though you may also want to give them the ability to spawn props with the E flag, if you want to find a list of flags look in the directory ingame and look under "flags".

**Comment by NDKilla** [comment]
It's worth noting that the p e and t flags for physgun, prop spawning, and toolgun MUST be lowercase. "/flaggive [name] pet" will give someone all 3 flags.

Secondly, I use ULX since in NS 1.1 most ingame admin commands are deprecated and in the code it actually says to get an external admin mod.

To the OP, you should use /flaggive pt for all character you want to have a physgun or toolgun.
There are ULX plugins that allow weapon giving, but it would have to be manually installed and given each time the player died or rejoined.
