### ISSUE TITLE
Stackable items [Suggestion]

### ISSUE THREAD

**Issue by DefenderVex** [Chessnut/NutScript#565]
Interesting feature idea (Might currently be a thing but i'm not sure).
An item flag that allows items of the same type to stack into one to save inventory space. Something like ITEM.stackable = true and ITEM.stackSize = 12.

**Comment by 7beat** [comment]
Good idea!

**Comment by blt950** [comment]
Ah this idea is nice. +1

**Comment by NDKilla** [comment]
Id love to have more chinese takeout in my suitcase ;D

**Comment by LukeCall** [comment]
I'd disagree with this due to the inventory being like that for a reason. You couldn't carry say 4+ Chinese Takeouts on your person at one time, nor could you fit around 10+ Chinese Takeouts in those suitcases. It also brings realism into place where you wouldn't pop another item into itself for a so called stack in real life now would you?

**Comment by DefenderVex** [comment]
Hence the reason for the 'ITEM.stackable = true' flag. Meaning that you can make items that would make sense to stack (Like a Chocolate Bar) while leaving items that wouldn't make sense to be stackable (Chinese Takeouts) non-stackable.

**Comment by LukeCall** [comment]
Would of thought someone would of experimented with code and emphasised a pull request of this by now.
