### ISSUE TITLE
Time reseting

### ISSUE THREAD

**Issue by blt950** [Chessnut/NutScript#571]
Each time I restart the server, the time starts at 12.00 PM again. 

The time should save on server shutdown/restarts, so it'll continue next time. This way the date will also go forward when it reaches next day.

Please also add option to use real-life-serverside-time. So I could for example have fiction date like 2017, but the time would be the same as server has.

**Comment by Chessnut** [comment]
Turns out the reason was because I forgot to load the time.

Also the time doesn't need to be saved on shutdown. Instead, I just save the first time the server starts. The IC date is then retrieved by getting the month/day/year from the configuration and adding the time different between the current time and the time when the server first started.
