### ISSUE TITLE
Whitelist Issue

### ISSUE THREAD

**Issue by PaXo0** [Chessnut/NutScript#680]
[ERROR] gamemodes/nutscript/gamemode/core/sh_commands.lua:489: attempt to call global 'L' (a table value)
1. onRun - gamemodes/nutscript/gamemode/core/sh_commands.lua:489
   1. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:145
   2. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:180
      1. Run - gamemodes/nutscript/gamemode/core/hooks/sv_hooks.lua:248
      2. unknown - gamemodes/nutscript/plugins/chatbox/sh_plugin.lua:69
      3. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
      4. unknown - lua/includes/extensions/net.lua:32

**Comment by lyxara** [comment]
First of all, have you changed something from the code?
Check the line 489 on the sh_commands.lua file if it's like this one:
`v:notifyLocalized("whitelist", client:Name(), target:Name(), L(faction.name, v))`

If `L` is used as `L faction.name` instead of `L()` function, change it.

If the line is the same, check if you have the sh_language.lua file in the 'core/libs/' folder.
You should have two functions `L()`, one for serverside and the other for clientside.

If you didn't fix your problems yet, try pulling the latest version of NutScript, because it works on my server at the latest version of NS and GMod...
