### ISSUE TITLE
Chat and "notes" issue.

### ISSUE THREAD

**Issue by pmx625** [Chessnut/NutScript#760]
Everything was working fine, however now whenever I type something in the IC radio or broadcast chats, that thing appears like this:

"<:: the thing I wrote ::>"

Anyway to solve this issue?

Also the notes plugins arent working. For some reason when you press "Use note", it just drops the note from your inventory and does nothing. I checked the server console and no errors appeared.

**Comment by MrSylar59** [comment]
For the note it's due to the fact that there are two entities named "nut_note" the first one in the note plugin and the second in the radio plugin (just change the names, it should work, I named mine "nut_starad.lua", works fine now.
Now for the second issue I didn't encountered it yet, the game mode is supposed to add those "<:: text ::>" only if the player who send the message is a combine (it's defined in hl2rp/schema/hooks/cl_hooks.lua (line 56)

**Comment by pmx625** [comment]
Once again, thank you for your help! I've fixed both issues!

**Comment by pmx625** [comment]
Regarding the notes issue, I changed the file's name in notes/entities/entities/ which was nut_note.lua to nut_notesboard.lua and notes still do not work. They just drop.

**Comment by MrSylar59** [comment]
You should have renamed the one in the radio plugin (something like nut_radio.lua shall be enough even though I didn't check if it needed a specific name, and I'll do that later) instead if you planed on using the notes

**Comment by pmx625** [comment]
This has been fixed! Thank you so much!
